/**
 * Loghub corpus loader for the bench harness.
 *
 * Each corpus is one file of newline-delimited raw log lines (the
 * Loghub `*_2k.log` or full corpus). The loader produces:
 *
 *   - `text`: one line per log, original Loghub format
 *   - `ndjson`: one OTLP-shaped JSON envelope per log
 *
 * Both are returned as `Buffer` so codec timings are end-to-end.
 *
 * Loghub-2k samples (2 K lines, ~few hundred KB each) are checked in
 * under `bench/corpora/loghub-2k/`. Larger corpora are downloaded by
 * `scripts/download-loghub.sh` into `bench/corpora/loghub-full/` and
 * gitignored.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Walk up from this file to find the package root (the directory
 * containing `package.json`). Works whether this module is loaded
 * from `bench/corpora.ts` (dev/typecheck) or `dist-bench/corpora.js`
 * (compiled).
 */
function findPackageRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "package.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(`Could not locate package root from ${import.meta.url}`);
}

const benchDir = join(findPackageRoot(), "bench");

export type CorpusName = "Apache" | "BGL" | "HDFS" | "Linux" | "OpenStack" | "OpenSSH";

export interface Corpus {
  name: CorpusName;
  size: "2k" | "full";
  /** Raw text body, one log per line. */
  text: Buffer;
  /** OTLP-shaped NDJSON, one envelope per log. */
  ndjson: Buffer;
  /**
   * Drain-templated form, one log per line as
   * `<template_id>\t<var1>\t<var2>\t…`. Present only if the
   * Drain fixture has been generated by
   * `bench/scripts/generate-drain-fixtures.py`.
   */
  drainText?: Buffer;
  /** Number of log lines. */
  count: number;
}

const FILENAMES: Record<CorpusName, string> = {
  Apache: "Apache_2k.log",
  BGL: "BGL_2k.log",
  HDFS: "HDFS_2k.log",
  Linux: "Linux_2k.log",
  OpenStack: "OpenStack_2k.log",
  OpenSSH: "OpenSSH_2k.log",
};

/** Returns the on-disk path for a (name, size) pair. */
export function corpusPath(name: CorpusName, size: "2k" | "full" = "2k"): string {
  if (size === "2k") {
    return join(benchDir, "corpora", "loghub-2k", FILENAMES[name]);
  }
  // For full corpora we use the underlying basename (no `_2k` suffix).
  return join(benchDir, "corpora", "loghub-full", `${name}.log`);
}

/** True if the corpus file is present on disk. */
export function corpusAvailable(name: CorpusName, size: "2k" | "full" = "2k"): boolean {
  return existsSync(corpusPath(name, size));
}

/** Wrap one log line in an OTLP-shaped JSON envelope. */
function wrapOtlp(name: CorpusName, line: string): string {
  return JSON.stringify({
    timestamp: 0,
    body: line,
    severity: "INFO",
    resource: { "service.name": name.toLowerCase() },
  });
}

/** Returns the on-disk path for a Drain-templated fixture. */
function drainPath(name: CorpusName, size: "2k" | "full" = "2k"): string {
  const subdir = size === "2k" ? "loghub-2k-drain" : "loghub-full-drain";
  return join(benchDir, "corpora", subdir, `${name}_drain.txt`);
}

/**
 * Load and prepare a single corpus. Returns the raw text, the
 * OTLP-NDJSON-wrapped form, and (optionally) the Drain-templated form
 * if the fixture has been generated. Trailing empty lines are dropped.
 */
export function loadCorpus(name: CorpusName, size: "2k" | "full" = "2k"): Corpus {
  const path = corpusPath(name, size);
  if (!existsSync(path)) {
    throw new Error(
      `Corpus not found: ${name} (${size}). Expected at ${path}. ` +
        `Run scripts/download-loghub.sh to fetch.`
    );
  }
  const raw = readFileSync(path, "utf8");
  const lines = raw.split("\n").filter((l) => l.length > 0);
  const text = Buffer.from(`${lines.join("\n")}\n`);
  const ndjson = Buffer.from(`${lines.map((l) => wrapOtlp(name, l)).join("\n")}\n`);

  const dPath = drainPath(name, size);
  const drainText = existsSync(dPath) ? readFileSync(dPath) : undefined;

  return drainText
    ? { name, size, text, ndjson, drainText, count: lines.length }
    : { name, size, text, ndjson, count: lines.length };
}

export const ALL_CORPORA: CorpusName[] = ["Apache", "BGL", "HDFS", "Linux", "OpenStack", "OpenSSH"];

/** Load every available corpus at the given size. Skips ones not on disk. */
export function loadAllAvailable(size: "2k" | "full" = "2k"): Corpus[] {
  return ALL_CORPORA.filter((n) => corpusAvailable(n, size)).map((n) => loadCorpus(n, size));
}
