import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { formatComparisonMarkdown } from "./format-comparison-markdown.js";
import type { ComparisonResult } from "./types.js";

function makeResult(entries: ComparisonResult["entries"]): ComparisonResult {
  return {
    entries,
    hasRegression: entries.some((entry) => entry.status === "regressed"),
  };
}

describe("formatComparisonMarkdown", () => {
  it("formats a mixed benchmark and monitor comparison", () => {
    const result = makeResult([
      {
        benchmark: "full-agent-dissect",
        metric: "events_per_sec",
        unit: "events/sec",
        direction: "bigger_is_better",
        baseline: 13240.5,
        current: 12500.25,
        percentChange: -5.59,
        status: "regressed",
      },
      {
        benchmark: "full-agent-dissect",
        metric: "service_rss_mb",
        unit: "MB",
        direction: "smaller_is_better",
        baseline: 543.1,
        current: 520.2,
        percentChange: -4.22,
        status: "improved",
      },
      {
        benchmark: "_monitor/system",
        metric: "cpu_user_pct",
        unit: "%",
        direction: "smaller_is_better",
        baseline: 67.4,
        current: 71.2,
        percentChange: 5.64,
        status: "regressed",
      },
    ]);

    const markdown = formatComparisonMarkdown(result, {
      title: "PR benchmark comparison",
      currentCommit: "abcdef1234567890",
      currentRef: "refs/pull/42/merge",
      currentLabel: "PR",
      baselineLabel: "main",
    });

    assert.equal(
      markdown,
      `## PR benchmark comparison
Comparing results for commit \`abcdef12\` on ref \`PR #42\`.

### Regressions

| Benchmark | Metric | main | PR | Δ% | Status |
| --- | --- | --- | --- | --- | --- |
| \`_monitor/system\` | \`cpu_user_pct\` | 67.4 % | 71.2 % | +5.64% | regressed ↑ |
| \`full-agent-dissect\` | \`events_per_sec\` | 13,241 events/sec | 12,500 events/sec | -5.59% | regressed ↓ |

### Benchmark Metrics

| Benchmark | Metric | main | PR | Δ% | Status |
| --- | --- | --- | --- | --- | --- |
| \`full-agent-dissect\` | \`events_per_sec\` | 13,241 events/sec | 12,500 events/sec | -5.59% | regressed ↓ |
| \`full-agent-dissect\` | \`service_rss_mb\` | 543.1 MB | 520.2 MB | -4.22% | improved ↓ |

### Monitor Metrics

| Benchmark | Metric | main | PR | Δ% | Status |
| --- | --- | --- | --- | --- | --- |
| \`_monitor/system\` | \`cpu_user_pct\` | 67.4 % | 71.2 % | +5.64% | regressed ↑ |

<details>
<summary>Per-metric detail</summary>

#### \`cpu_user_pct\`

| Benchmark | Metric | main | PR | Δ% | Status |
| --- | --- | --- | --- | --- | --- |
| \`_monitor/system\` | \`cpu_user_pct\` | 67.4 % | 71.2 % | +5.64% | regressed ↑ |

#### \`events_per_sec\`

| Benchmark | Metric | main | PR | Δ% | Status |
| --- | --- | --- | --- | --- | --- |
| \`full-agent-dissect\` | \`events_per_sec\` | 13,241 events/sec | 12,500 events/sec | -5.59% | regressed ↓ |

#### \`service_rss_mb\`

| Benchmark | Metric | main | PR | Δ% | Status |
| --- | --- | --- | --- | --- | --- |
| \`full-agent-dissect\` | \`service_rss_mb\` | 543.1 MB | 520.2 MB | -4.22% | improved ↓ |

</details>

Generated by [octo11y](https://github.com/strawgate/octo11y).`,
      );
  });

  it("keeps non-PR refs unchanged in the header", () => {
    const markdown = formatComparisonMarkdown(makeResult([]), {
      title: "Comparison summary",
      currentRef: "refs/heads/main",
    });
    assert.match(markdown, /ref `refs\/heads\/main`/);
  });

  it("keeps refs/pull/N/head unchanged in the header", () => {
    const markdown = formatComparisonMarkdown(makeResult([]), {
      title: "Comparison summary",
      currentRef: "refs/pull/42/head",
    });
    assert.match(markdown, /ref `refs\/pull\/42\/head`/);
  });

  it("reports no regressions cleanly", () => {
    const result = makeResult([
      {
        benchmark: "passthrough",
        metric: "events_per_sec",
        unit: "events/sec",
        direction: "bigger_is_better",
        baseline: 1000,
        current: 1100,
        percentChange: 10,
        status: "improved",
      },
    ]);

    const markdown = formatComparisonMarkdown(result, { includeDetails: false });
    assert.match(markdown, /No regressions detected\./);
    assert.match(markdown, /### Benchmark Metrics/);
    assert.doesNotMatch(markdown, /Per-metric detail/);
  });

  it("handles empty comparisons as no baseline data", () => {
    const markdown = formatComparisonMarkdown(makeResult([]), {
      title: "Comparison summary",
    });
    assert.equal(
      markdown,
      `## Comparison summary

No comparable baseline data found.

Generated by [octo11y](https://github.com/strawgate/octo11y).`,
    );
  });

  it("limits the regression summary when maxRegressions is set", () => {
    const result = makeResult([
      {
        benchmark: "bench-a",
        metric: "ns_per_op",
        unit: "ns/op",
        direction: "smaller_is_better",
        baseline: 100,
        current: 120,
        percentChange: 20,
        status: "regressed",
      },
      {
        benchmark: "bench-b",
        metric: "ns_per_op",
        unit: "ns/op",
        direction: "smaller_is_better",
        baseline: 100,
        current: 125,
        percentChange: 25,
        status: "regressed",
      },
    ]);

    const markdown = formatComparisonMarkdown(result, { maxRegressions: 1 });
    assert.match(markdown, /Showing 1 of 2 regressions\./);
  });
});
