import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { formatComparisonMarkdown } from "./format-comparison-markdown.js";
import type { ComparisonResult } from "./types.js";

function makeResult(entries: ComparisonResult["entries"]): ComparisonResult {
  return {
    entries,
    hasRegression: entries.some((entry) => entry.status === "regressed"),
  };
}

describe("formatComparisonMarkdown", () => {
  it("formats a mixed benchmark and monitor comparison", () => {
    const result = makeResult([
      {
        benchmark: "full-agent-dissect",
        lane: "full-agent-dissect [collector=otelcol]",
        tags: { collector: "otelcol" },
        laneClass: "required",
        metric: "events_per_sec",
        unit: "events/sec",
        direction: "bigger_is_better",
        baseline: 13240.5,
        current: 12500.25,
        percentChange: -5.59,
        status: "regressed",
      },
      {
        benchmark: "full-agent-dissect",
        lane: "full-agent-dissect [collector=otelcol]",
        tags: { collector: "otelcol" },
        laneClass: "required",
        metric: "service_rss_mb",
        unit: "MB",
        direction: "smaller_is_better",
        baseline: 543.1,
        current: 520.2,
        percentChange: -4.22,
        status: "improved",
      },
      {
        benchmark: "_monitor/system",
        metric: "cpu_user_pct",
        unit: "%",
        direction: "smaller_is_better",
        baseline: 67.4,
        current: 71.2,
        percentChange: 5.64,
        status: "regressed",
      },
    ]);

    const markdown = formatComparisonMarkdown(result, {
      title: "PR benchmark comparison",
      currentCommit: "abcdef1234567890",
      currentRef: "refs/pull/42/merge",
      currentLabel: "PR",
      baselineLabel: "main",
    });

    assert.match(markdown, /## PR benchmark comparison/);
    assert.match(markdown, /Comparing results for commit `abcdef12` on ref `PR #42`/);
    assert.match(markdown, /\| Lane \| Class \| Metric \| main \| PR \| Δ% \| Status \|/);
    assert.match(markdown, /\| `full-agent-dissect \[collector=otelcol\]` \| `required` \| `events_per_sec`/);
    assert.match(markdown, /\| `_monitor\/system` \| `cpu_user_pct`/);
    assert.match(markdown, /Generated by \[octo11y\]/);
  });

  it("keeps non-PR refs unchanged in the header", () => {
    const markdown = formatComparisonMarkdown(makeResult([]), {
      title: "Comparison summary",
      currentRef: "refs/heads/main",
    });
    assert.match(markdown, /ref `refs\/heads\/main`/);
  });

  it("keeps refs/pull/N/head unchanged in the header", () => {
    const markdown = formatComparisonMarkdown(makeResult([]), {
      title: "Comparison summary",
      currentRef: "refs/pull/42/head",
    });
    assert.match(markdown, /ref `refs\/pull\/42\/head`/);
  });

  it("reports no regressions cleanly", () => {
    const result = makeResult([
      {
        benchmark: "passthrough",
        metric: "events_per_sec",
        unit: "events/sec",
        direction: "bigger_is_better",
        baseline: 1000,
        current: 1100,
        percentChange: 10,
        status: "improved",
      },
    ]);

    const markdown = formatComparisonMarkdown(result, { includeDetails: false });
    assert.match(markdown, /No regressions detected\./);
    assert.match(markdown, /### Benchmark Metrics/);
    assert.doesNotMatch(markdown, /Per-metric detail/);
  });

  it("handles empty comparisons as no baseline data", () => {
    const markdown = formatComparisonMarkdown(makeResult([]), {
      title: "Comparison summary",
    });
    assert.equal(
      markdown,
      `## Comparison summary

No comparable baseline data found.

Generated by [octo11y](https://github.com/strawgate/octo11y).`,
    );
  });

  it("includes matrix summary and missing lane outcomes without baseline data", () => {
    const markdown = formatComparisonMarkdown({
      entries: [],
      hasRegression: false,
      matrix: {
        expectedCount: 3,
        observedCount: 2,
        missingResultCount: 1,
        requiredPassedCount: 1,
        requiredFailedCount: 0,
        probePassedCount: 0,
        probeFailedCount: 1,
        hasRequiredFailure: false,
        lanes: [
          {
            key: "lane-a",
            label: "collector=otelcol, target_eps=10",
            dimensions: { collector: "otelcol", target_eps: "10" },
            laneClass: "required",
            status: "passed",
          },
          {
            key: "lane-b",
            label: "collector=otelcol, target_eps=10000",
            dimensions: { collector: "otelcol", target_eps: "10000" },
            laneClass: "probe",
            status: "failed",
          },
          {
            key: "lane-c",
            label: "collector=otelcol, target_eps=max",
            dimensions: { collector: "otelcol", target_eps: "max" },
            laneClass: "probe",
            status: "missing",
          },
        ],
      },
    });

    assert.match(markdown, /### Matrix Summary/);
    assert.match(markdown, /\| Expected \| Observed \| Missing \| Required Failed \| Probe Failed \|/);
    assert.match(markdown, /\| 3 \| 2 \| 1 \| 0 \| 1 \|/);
    assert.match(markdown, /### Matrix Lane Outcomes/);
    assert.match(markdown, /collector=otelcol, target_eps=10000/);
    assert.match(markdown, /collector=otelcol, target_eps=max/);
    assert.match(markdown, /No comparable baseline data found\./);
  });

  it("renders unmapped lane classes as blank markers instead of required", () => {
    const markdown = formatComparisonMarkdown(makeResult([
      {
        benchmark: "bench-a",
        lane: "bench-a [collector=otelcol]",
        laneClass: "required",
        metric: "ns_per_op",
        unit: "ns/op",
        direction: "smaller_is_better",
        baseline: 100,
        current: 120,
        percentChange: 20,
        status: "regressed",
      },
      {
        benchmark: "_monitor/system",
        metric: "cpu_user_pct",
        unit: "%",
        direction: "smaller_is_better",
        baseline: 67.4,
        current: 71.2,
        percentChange: 5.64,
        status: "regressed",
      },
    ]));

    assert.match(markdown, /\| `_monitor\/system` \| `—` \| `cpu_user_pct`/);
  });

  it("limits the regression summary when maxRegressions is set", () => {
    const result = makeResult([
      {
        benchmark: "bench-a",
        metric: "ns_per_op",
        unit: "ns/op",
        direction: "smaller_is_better",
        baseline: 100,
        current: 120,
        percentChange: 20,
        status: "regressed",
      },
      {
        benchmark: "bench-b",
        metric: "ns_per_op",
        unit: "ns/op",
        direction: "smaller_is_better",
        baseline: 100,
        current: 125,
        percentChange: 25,
        status: "regressed",
      },
    ]);

    const markdown = formatComparisonMarkdown(result, { maxRegressions: 1 });
    assert.match(markdown, /Showing 1 of 2 regressions\./);
  });
});
